### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by OffsetMonkey538** [OffsetMonkey538/OffsetConfig538#1]
- [ ] Fix JitPack building
- [ ] Custom (de)serializers
    - [ ] Find out if Simple-YAML already supports them, if not then figure out how to make it work.
    - [ ] Add (de)serializers for some common minecraft classes
        - [ ] PotionEffectInstance
        - [ ] think of some more common things people would want to use in a config.
- [ ] Mod menu integration
- [ ] Documentation
    - [ ] Readme
    - [ ] Javadoc
    - [ ] Github Wiki
